const paragraphs = [
    "Não acredite em algo simplesmente porque ouviu. Não acredite em algo simplesmente porque todos falam a respeito. Não acredite em algo simplesmente porque está escrito em seus livros religiosos. Não acredite em algo só porque seus professores e mestres dizem que é verdade. Não acredite em tradições só porque foram passadas de geração em geração. Mas, depois de muita análise e observação, se você vê que algo concorda com a razão e que conduz ao bem e benefício de todos, aceite-o e viva-o..",
    "Podemos acreditar que tudo que a vida nos oferecerá no futuro é repetir o que fizemos ontem e hoje. Mas, se prestarmos atenção, vamos nos dar conta de que nenhum dia é igual a outro. Cada manhã traz uma bênção escondida; uma bênção que só serve para esse dia e que não se pode guardar nem desaproveitar. Se não usamos este milagre hoje, ele vai se perder. Este milagre está nos detalhes do cotidiano; é preciso viver cada minuto porque ali encontramos a saída de nossas confusões, a alegria de nossos bons momentos, a pista correta para a decisão que tomaremos. Nunca podemos deixar que cada dia pareça igual ao anterior porque todos os dias são diferentes, porque estamos em constante processo de mudança..",
    "Uma coisa é você achar que está no caminho certo, outra é achar que o seu caminho é o único. Nunca podemos julgar a vida dos outros, porque cada um sabe da sua própria dor e renúncia..",
    "Conta a lenda que tudo que cai nas águas deste rio - as folhas, os insetos, as penas das árvores, se transforma em pedras do seu leito. Ahh, quem dera se eu pudesse arrancar o coração do meu peito e atirá-lo na correnteza, e então não haveria mais dor, nem saudade, nem lembranças....",
    "O guerreiro da luz aprendeu que Deus usa a solidão para ensinar a convivência. Usa a raiva para mostrar o infinito valor da paz. Usa o tédio para ressaltar a importância da aventura e do abandono. Deus usa o silêncio para ensinar sobre a responsabilidade das palavras. Usa o cansaço para que se possa compreender o valor do despertar. Usa a doença para ressaltar a benção da saúde. Deus usa o fogo para ensinar sobre a água. Usa a terra para que se compreenda o valor do ar. Usa a morte para mostrar a importância da vida.",
    "No amor ninguém pode machucar ninguém; cada um é responsável por aquilo que sente e não podemos culpar o outro por isso... Já me senti ferida quando perdi o homem por quem me apaixonei... Hoje estou convencida de que ninguém perde ninguém, porque ninguém possui ninguém... Essa é a verdadeira experiência de ser livre: ter a coisa mais importante do mundo sem possuí-la.",
    "Quando renunciamos aos nossos sonhos e encontramos a paz - disse ele depois de um tempo - temos um pequeno período de tranquilidade. Mas os sonhos mortos começam a apodrecer dentro de nós, e infestar todo o ambiente em que vivemos. Começamos a nos tornar cruéis com aqueles que nos cercam, e finalmente passamos a dirigir esta crueldade contra nós mesmos. Surgem as doenças e psicoses. O que queríamos evitar no combate - a decepção e a derrota - passa a ser o único legado de nossa covardia. E, um belo dia, os sonhos mortos e apodrecidos tornam o ar difícil de respirar e passamos a desejar a morte, a morte que nos livrasse de nossas certezas, de nossas ocupações, e daquela terrível paz das tardes de domingo..",
    "A Dor coletiva gera união.",
    
];